### ISSUE TITLE
Error in guide_train.colorplane(guide, scale, output) :    unused argument (output)

### ISSUE THREAD

**Issue by tastapiano** [wmurphyrd/colorplaner#42]
Using the example provided in the documentation, and also own examples I get the following error from guide_train.colorplane: unused argument (output)

R version 3.5.0 (2018-04-23) 
Platform: x86_64-w64-mingw32/x64 (64-bit)
colorplaner 1.0.3

```
> if(require(mapproj)) {
+     crimes <- data.frame(state = tolower(rownames(USArrests)), USArrests)
+     states_map <- map_data("state")
+     ggplot(crimes, aes(map_id = state, fill = Murder, fill2 = UrbanPop)) +
+       geom_map(map = states_map) +
+       scale_fill_colorplane() +
+       expand_limits(x = states_map$long, y = states_map$lat) +
+       coord_map() 
+   }
Error in guide_train.colorplane(guide, scale, output) : 
  unused argument (output)
```

**Comment by wmurphyrd** [comment]
Wow that got reported fast! There is an update needed for the new version of ggplot2. You can install it with `devtools::install_github("wmurphyrd/colorplaner")` (if you have devtools installed), and I'll be submitting it to CRAN soon.
