### ISSUE TITLE
Colorplaner Compatibilty with ggplot2  v 2_3.0.0

### ISSUE THREAD

**Issue by asreece** [wmurphyrd/colorplaner#45]
Hi.  
Colorplaner is a terrific package.  It seems to work just fine with ggplot2 2.2.1, but not with ggplot2 v 2_3.0.0 or V 2_3.0.0.9000 the dev version. 
However ggplot2 v 2_3.0.0 is needed for geom_sf and sf compatability.
Are there plans for an update to keep up with ggplot2 modifications????
Thanks so much,
Stuart.

**Comment by Grelot** [comment]
Same here, i'm using ggplot 3.1.0
and got the following error : 
Error in guide_train.colorplane(guide, scale, output) : 
  unused argument (output)

that's very sad because this package is really awesome.

**Comment by wmurphyrd** [comment]
I have a new version that works with ggplot2 3.0.0 & 3.1.0 but I missed a deadline to get it up on CRAN, so you'll have to install it form github:

`devtools::install_github("wmurphyrd/colorplaner")`

**Comment by asreece** [comment]
Dear William,

Thankyou great!!

I think this is a simply wonderful package and I plane to feature it in some up-coming papers!!

Thankyou again every so much,

Stuart.
